### PR TITLE
Added Towny Page

### PR DESCRIPTION
**Pull request by liv-kami**

### CODE REVIEW

**Comment by liv-kami** [comment]
wait forgot something ugh

**Comment by liv-kami** [comment]
fixed, ready

**Comment by liv-kami** [comment]
just changed cause there was a caps issue ^

**Comment by JustAMatt** [comment]
Please elaborate a bit more on this mechanic since it's the core of adk. Talk a bit about the unique opportunities for towns with brew and mines, if someone should make or join a town, also incorporate in the command list qwq

**Comment by liv-kami** [comment]
will do later qwq

**Comment by liv-kami** [comment]
Updated towny md

**Pull request merged**
